### ISSUE TITLE
Invalid tag "/zabbix_export"

### ISSUE THREAD

**Issue by mrRobit** [mrRobit/Zabbix_templates#11]
Invalid tag "/zabbix_export": unexpected tag "date" - when I try import you new XML, Json or yaml file.

**Comment by fivedna** [comment]
OK, when I try import your 3 files, it has 1 error: "Invalid tag "/zabbix_export": unexpected tag "date""

**Comment by fivedna** [comment]
Hello Mr. @mrRobit, do you repair that error: "Invalid tag "/zabbix_export": unexpected tag "date" ??

**Comment by mrRobit** [comment]
@fivedna remove the <date> section in the file.
I will need to do comprehensive testing before uploading a new version. It behaves differently on different zabbix installations. Will take some time

**Comment by jangliss** [comment]
If you delete the `date` field, and rename the `group` to `template_group` it imports, from my preliminary testing.

**Comment by fivedna** [comment]
> If you delete the `date` field, and rename the `group` to `template_group` it imports, from my preliminary testing.

I try to remove date field, but it will has error with next field is "groups" field.

@mrRobit: in your file, I see the character such as: &lt; or    <description>ENTITY-SENSOR-MIB::entPhySensorValue**&amp;**#13;
**&amp;**#13; ....
I don't know is it the error from here?
THanks!

**Comment by fivedna** [comment]
I'm import the template palo_alto_firewall in this link: https://www.zabbix.com/integrations/palo_alto_networks

 It shows somethings, but the Linkstatus with OID: 1.3.6.1.2.1.2.2.1.8. and the traffic out and in on interface I can't see it. How can I resolve this problem?

I check the palo_alto_firewll.xml file before import, It has link status OID and traffic in/out OID, example.

```
<item_prototype>
                            <name>Outgoing traffic on interface $1</name>
                            <type>4</type>
                            <snmp_community>{$SNMP_COMMUNITY}</snmp_community>
                            <snmp_oid>.1.3.6.1.2.1.2.2.1.16.{#SNMPINDEX}</snmp_oid>
                            <key>ifOutOctets[{#SNMPVALUE}]</key>
```
My PaloAlto device is PA 850 and PA 440, OS is 11.0.1.

**Comment by jangliss** [comment]
> > If you delete the `date` field, and rename the `group` to `template_group` it imports, from my preliminary testing.
> 
> I try to remove date field, but it will has error with next field is "groups" field.

Literally my instructions were "delete date and rename group to template_group". Did you try that?

**Comment by jangliss** [comment]
> I'm import the template palo_alto_firewall in this link: https://www.zabbix.com/integrations/palo_alto_networks
> 
> It shows somethings, but the Linkstatus with OID: 1.3.6.1.2.1.2.2.1.8. and the traffic out and in on interface I can't see it. How can I resolve this problem?

From the README "Overview" section https://github.com/mrRobit/Zabbix_templates#overview

> TIP: to monitor firewalls interfaces, please add offcial zabbix template: [Template Module Interfaces SNMPv2](https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/module/interfaces_snmp?at=refs%2Fheads%2Frelease%2F5.0).

**Comment by fivedna** [comment]
> > > If you delete the `date` field, and rename the `group` to `template_group` it imports, from my preliminary testing.
> > 
> > 
> > I try to remove date field, but it will has error with next field is "groups" field.
> 
> Literally my instructions were "delete date and rename group to template_group". Did you try that?

Of course
`<?xml version="1.0" encoding="UTF-8"?>
<zabbix_export>
    <version>6.4</version>
    <groups>
        <group>
            <uuid>7df96b18c230490a9a0a9e2307226338</uuid>
            <name>Templates_group</name>
        </group>
    </groups>
    <templates>
        <template>
            <uuid>b8c9c61f2aa9496084edea293b792b9f</uuid>
            <template>Template Palo Alto Firewall</template>
            <name>Template Palo Alto Firewall</name>
            <groups>
                <group>
                    <name>Templates_group</name>
                </group>
            </groups>
            <items>
                <item>
                    <uuid>a1ab5a14371940148deec735738f05fa</uuid>`

**Comment by jangliss** [comment]
> > > > If you delete the `date` field, and rename the `group` to `template_group` it imports, from my preliminary testing.
> > > 
> > > 
> > > I try to remove date field, but it will has error with next field is "groups" field.
> > 
> > 
> > Literally my instructions were "delete date and rename group to template_group". Did you try that?
> 
> Of course `<?xml version="1.0" encoding="UTF-8"?> <zabbix_export> <version>6.4</version> <groups> <group> <uuid>7df96b18c230490a9a0a9e2307226338</uuid> <name>Templates_group</name> </group> </groups> <templates> <template> <uuid>b8c9c61f2aa9496084edea293b792b9f</uuid> <template>Template Palo Alto Firewall</template> <name>Template Palo Alto Firewall</name> <groups> <group> <name>Templates_group</name> </group> </groups> <items> <item> <uuid>a1ab5a14371940148deec735738f05fa</uuid>`

Not quite what I'd meant, but close.  It's complaining that the `<groups>` tag is invalid on the 6.4 import.  Using the yaml file, I did the following:

```
zabbix_export:
  version: '6.4'
  template_group:
    -
      uuid: 7df96b18c230490a9a0a9e2307226338
      name: Templates
```

Note that this is changing `groups` to `template_groups`. I'll have to look over my import again to remember if it's a plural or not. I suspect the XML format change would be `template_groups` and `template_group`, so something like:

```
    <template_groups>
        <template_group>
            <uuid>7df96b18c230490a9a0a9e2307226338</uuid>
            <name>Templates</name>
        </template_group>
    </template_groups>
```

But that's just a guess, I used the yaml format.

**Comment by peterjmcgrath** [comment]
I had to change 3 things to get  the yaml file importing on zabbix 6.4.7:

-Delete 'date:' line
-rename next line from  'groups:' to 'template_groups:'
-within the 'template_groups:' section, rename 'name: Template' to 'name: Templates'

Worked for me

**Comment by mrRobit** [comment]
I repaired the yaml file and now it should import correctly. Thank you for your patience.
