### ISSUE TITLE
Template incompatibility with Zabbix 6.0

### ISSUE THREAD

**Issue by marcop82** [mrRobit/Zabbix_templates#5]
When importing the template, the following error is given:
`Cannot import template "Template Palo Alto Firewall", linked template "Template Module Interfaces SNMPv2" does not exist.`

This is easily fixed by changing the name of the linked template in the template file to "Interfaces SNMP", which seems to be the correct version that's compatible (https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/module/interfaces_snmp)

**Comment by seanmmitchell** [comment]
After renaming, importing succeeded for me.

**Comment by fersion** [comment]
> When importing the template, the following error is given: `Cannot import template "Template Palo Alto Firewall", linked template "Template Module Interfaces SNMPv2" does not exist.`
> 
> This is easily fixed by changing the name of the linked template in the template file to "Interfaces SNMP", which seems to be the correct version that's compatible (https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/module/interfaces_snmp)

This also fixed the issue for me. Thank you for this!

**Comment by mrRobit** [comment]
I removed this linked template, as I do not have direct impact on it. You can still add it separately. which is also stated in the ReadMe file. Thanks
